# -*- coding: utf-8 -*-
"""FinalProjectPYTHONDATAENGINEER.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13fUemDo-Xpysd00x1V1XpN54BVWMJHYW
"""

#To get the exchange rates CSV file: wget https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMSkillsNetwork-PY0221EN-Coursera/labs/v2/exchange_rate.csv

from bs4 import BeautifulSoup
import numpy as np
import pandas as pd
import requests
from sqlalchemy import create_engine
from datetime import datetime
import sqlite3
import warnings

warnings.filterwarnings("ignore")

url = "https://web.archive.org/web/20230908091635/https://en.wikipedia.org/wiki/List_of_largest_banks"
table_attributes = ["Name", "MC_USD_Billion"]
final_attributes = ["Name", "MC_USD_Billion", "MC_GBP_Billion", "MC_EUR_Billion", "MC_INR_Billion"]
outputCSV = "./Largest_banks_data.csv"
db_name = "Banks.db"
table_name = "Largest_banks"


def log_progress(message):
    ''' This function logs the mentioned message of a given stage of the
    code execution to a log file. Function returns nothing'''
    timestamp = '%Y-%h-%d-%H:%M:%S'
    now = datetime.now()
    ts = now.strftime(timestamp)
    with open("./code_log.txt","a") as f:
        f.write(ts + " : " + message + "\n")

def extract(url, table_attribs):
    ''' This function aims to extract the required
    information from the website and save it to a data frame. The
    function returns the data frame for further processing. '''
    request = requests.get(url).text
    soup = BeautifulSoup(request, "html.parser")
    df = pd.DataFrame(columns = table_attribs)
    table = soup.find_all("tbody")
    rows = table[0].find_all("tr")
    for row in rows:
        if row.find('td') is not None:
            col = row.find_all("td")
            if len(col) != 0:
                data = {"Name" : col[1].find_all("a")[1]["title"],
                        "MC_USD_Billion" : float(col[2].contents[0][:-1])}
                df1 = pd.DataFrame(data, index = [0])
                df = pd.concat([df,df1], ignore_index = True)
    #print(df)
    return df

def transform(df, csv_path):
    ''' This function accesses the CSV file for exchange rate
    information, and adds three columns to the data frame, each
    containing the transformed version of Market Cap column to
    respective currencies'''
    exchange_rate = pd.read_csv("./exchange_rate.csv")
    dictionary = exchange_rate.set_index("Currency").to_dict()["Rate"]

    df['MC_GBP_Billion'] = [np.round(x*dictionary['GBP'],2) for x in df['MC_USD_Billion']]
    df['MC_EUR_Billion'] = [np.round(x*dictionary['EUR'],2) for x in df['MC_USD_Billion']]
    df['MC_INR_Billion'] = [np.round(x*dictionary['INR'],2) for x in df['MC_USD_Billion']]

    #print(df)
    return df

def load_to_csv(df, output_path):
    ''' This function saves the final data frame as a CSV file in
    the provided path. Function returns nothing.'''
    df.to_csv(output_path, index=False)

def load_to_db(df, sql_connection, table_name):
    ''' This function saves the final data frame to a database
    table with the provided name. Function returns nothing.'''
    df.to_sql(table_name,sql_connection, if_exists = "replace", index = False)

def run_query(query_statement, sql_connection):
    ''' This function runs the query on the database table and
    prints the output on the terminal. Function returns nothing. '''
    print(query_statement + " ")
    print(pd.read_sql(query_statement, sql_connection))
''' Here, you define the required entities and call the relevant
functions in the correct order to complete the project. Note that this
portion is not inside any function.'''

log_progress("Preliminaries complete. Initiating ETL process")

df = extract(url, table_attributes)
log_progress("Data extraction complete. Initiating Transformation process")

df = transform(df, "./code_log.txt")
log_progress("Data transformation complete. Initiating Loading process")

load_to_csv(df, outputCSV)
log_progress("Data saved to CSV file")

conn = sqlite3.connect(db_name)
log_progress("SQL Connection initiated")

load_to_db(df, conn, table_name)
log_progress("Data loaded to Database as a table, Executing queries")

run_query(f"SELECT Name from {table_name} LIMIT 5",conn)
log_progress("Process Complete")

conn.close()
log_progress("Server Connection closed")